### ISSUE TITLE
[ELE-1389] Sending Alerts to Different Channels

### ISSUE THREAD

**Issue by lord-skinner** [elementary-data/elementary#1010]
**Is your feature request related to a problem? Please describe.**
Sort of. Currently we are configuring a channel in our `models.yml` files for alters to go to, but the `edr` cli requires you as a token/channel and that channel overrides what is in the `models.yml`. If you pass a webhook, that is associated with a specific channel, again overriding the configured channel in our `models.yml` file.

**Describe the solution you'd like**
We'd like for the channel passed into `edr` to be the default channel, and the channel in the config, if exists, to override it. Pushing alerts with no configured channel to the default channel.

**Describe alternatives you've considered**
We have used the `--select` command to send only specifically tagged models to the channel passed into `edr`, but this is redundent configuration and requires multiple separate jobs/commands to be handle and again disregards the configured channel in our yaml. 

**Would you be willing to contribute this feature?**
Possibly

<sub>[ELE-1389](https://linear.app/elementary/issue/ELE-1389/sending-alerts-to-different-channels)</sub>

**Comment by haritamar** [comment]
Hi @lord-skinner !
Thanks for opening this issue and sorry for the super delayed response.
I believe that this behavior was changed since and we no longer override the channel by default (controlled with the `--override-dbt-project-config` which is False by default).

If I'm wrong / missing something please feel free to re-open the issue.
