### ISSUE TITLE
Python model failed due to elementary package issue

### ISSUE THREAD

**Issue by pavandivve** [elementary-data/elementary#1179]
**Describe the bug**
We have recently started using Elementary package in our dbt project. it all working fine until a week ago. but suddenly our DBT pipeline started failing with error in one of the Python model with error "Materialization "materialization_table_snowflake" only supports languages ['sql']; got "python". we raised the issue with DBT support they then identified that it is because of elementary pacakge and issue got resolved with updating package version.  we wondered how elementary package affected python model with out proper error message. can you please look into this and suggest why the problem occurred and how to fix those kind of issues in future.

**To Reproduce**

1. Go to 'dbt project' and add below python model with elementary version 0.9.4.

# snowflake
import pandas as pd
def model(dbt, session):
    return pd.DataFrame({"id": [1]})

2. Run above python model
3. See error

**Expected behavior**
Python model should run successfully

**Screenshots**

**Environment (please complete the following information):**

- dbt package Version: 0.9.4

**Additional context**

**Comment by haritamar** [comment]
Hi @pavandivve !
Thanks for opening this issue and sorry for the super delayed response, we are currently in the process of reviewing our open issues and improving our process there.
Since the issue has been open for over 3 months I'm going to go ahead to close it - please feel free to re-open if still relevant.

Thanks!
Itamar
