### ISSUE TITLE
Error while trying to download elementary. Error is FileNotFoundError: [Errno 2] No such file or directory: 'dbt_packages\\dbt-data-reliability-0.12.2\\integration_tests\\deprecated_tests\\macros\\unit_testecated_tests\\macros\\unit_tests\\test_adapter_specific_macros_have_default_implementation.sql'

### ISSUE THREAD

**Issue by shamilsaeed** [elementary-data/elementary#1355]
I am running dbt deps using poetry. Anytime I add elementary package to packages.yml 

```
  - package: elementary-data/elementary
    version: 0.12.2
```
    
  and I do 
  
  `poetry run dbt deps` I get 

FileNotFoundError: [Errno 2] No such file or directory: 'dbt_packages\\dbt-data-reliability-0.12.2\\integration_tests\\deprecated_tests\\macros\\unit_testecated_tests\\macros\\unit_tests\\test_adapter_specific_macros_have_default_implementation.sql'

Seems like I have all permissions, as other dbt packages (dbt_utils, dbt_expecations) download properly.

**Comment by haritamar** [comment]
Hi @shamilsaeed !
Thanks for opening this issue and sorry for the delayed response, we are currently in the process of reviewing our open issues and improving our process there.
Since the issue has been open for over 3 months I'm going go ahead to close it - please feel free to re-open if still relevant.

Thanks!
Itamar
