### ISSUE TITLE
Issue rendering report with edr command - dbt tree structure not showing

### ISSUE THREAD

**Issue by mattxxi** [elementary-data/elementary#1376]
**Describe the bug**
When I generate dashboard with edr command I do not see the dbt tree structure anymore when I navigate in lineage tab.

**To Reproduce**
This problem appears randomly, I had the tree structure before

**Expected behavior**
I should be able to navigate in the DBT tree structure

**Screenshots**
![image](https://github.com/elementary-data/elementary/assets/36408416/da96090b-0415-4dc3-bf62-f0d5eacfb4e0)

**Environment (please complete the following information):**

- edr Version: 0.13.2
- dbt package Version: 0.13.1

**Comment by haritamar** [comment]
Hi @mattxxi !
Thanks for opening this issue and sorry for the delayed response, we are currently in the process of reviewing our open issues and improving our process there.
Since the issue has been open for over 3 months I'm going go ahead to close it - please feel free to re-open if still relevant.

Thanks!
Itamar
