### ISSUE TITLE
when using python 3.11 getting "ImportError: cannot import name 'Mapping' from 'collections'"

### ISSUE THREAD

**Issue by roy-wenrix** [elementary-data/elementary#1392]
when using python 3.11 getting "ImportError: cannot import name 'Mapping' from 'collections'"

env: python 3.11 and above
cli: edr report --file-path "report.html"

expected the report, getting error:  "ImportError: cannot import name 'Mapping' from 'collections'"

- edr Versionelementary-data==0.13.2
- dbt package Version: 1.4

**Comment by haritamar** [comment]
Hi @roy-wenrix ,
Thanks for opening this issue and sorry for the delayed response, we are currently in the process of reviewing our open issues and improving our process there.
Since the issue has been open for over 3 months I'm going go ahead to close it - please feel free to re-open if still relevant.

Thanks!
Itamar
