### ISSUE TITLE
Set "elementary_tests" schema to upper case

### ISSUE THREAD

**Issue by ltw94** [elementary-data/elementary#244]
Hi,

I'm using elementary with Snowflake, where we have set all of our schemas as upper-case. However, in the elementary dbt package the "__tests" is hard-coded as lower-case resulting in a schema named "ELEMENTARY__tests".

Can you give the option of creating a var for this so we have the option of lower-case or upper-case suffix for "__tests".

(Raised this via slack here: https://elementary-community.slack.com/archives/C02CTC89LAX/p1660646926498189)

Thanks!

**Comment by oravi** [comment]
Hi @ltw94 ! thanks so much for opening this issue. 

Here's a short background on our current schemas - 

- If a user follows our setup guideline - when you run elementary using `dbt run -s elementary` it creates all the elementary aggregated tables (metrics, alerts, dbt artifacts tables) in a `<default_schema>_elementary` schema as defined in your dbt_project.yml 
- When you run elementary tests using `dbt test` it also creates for each test a table for metrics and anomalies in a `<default_schema>_elementary__tests` schema. The `__tests` suffix is hardcoded and we could fix it to be determined dynamically  

Here's a suggestion on what's needed to support this - 

1. Add a var that indicates the elementary custom tests schema (could be named 'elementary_tests_schema'). We have a macro called `get_config_var` which contains all the vars in the project with their defaults. So you can simply add this new var to this macro with a default value of `__tests` to keep backwards compatibility. Please note that in order to use these defaults when accessing a var in Elementary, we use `elementary.get_config_var` instead of dbt `var` macro directly. 
2. If this var will be overridden by the user with a none value, we won't create a tests schema and all the tests tables will be created in the same `<default_schema>_elementary` as described above. To support this behaviour you should change the macro `create_elementary_tests_schema` to skip the schema creation if the `elementary_tests_schema` var value is none.
3. Then we just need to replace the hardcoded references to `__tests` with - `elementary.get_config_var('elementary_tests_schema')`. The files referencing it are - 
   - test_table_anomalies
   - test_dimension_anomalies
   - test_column_anomalies
   - test_all_columns_anomalies
   - test_schema_changes
   - create_elementary_tests_schema
   - handle_test_results

Tests and everything should remain the same as this suggestion keeps backwards competibility.
Please let me know if you have any further questions or suggestions!

**Comment by Vfisa** [comment]
Hi, I just wanted to chip in here after a discussion on the slack - I have similar issue where the option is to keep all tables, incl. test one in my defined schema. I would really love to have an option to define this as well. (not to use `__test` by my defined schema)

**Comment by Maayan-s** [comment]
https://github.com/elementary-data/dbt-data-reliability/pull/86

**Comment by Maayan-s** [comment]
The good news are we implemented a custom suffix for the tests schema - @ltw94 

The bad news are that it can't be empty at the moment. - @Vfisa 

We encountered an issue with dbt that prevents that, in a nutshell - they create a cached schema at the run start and use it later as default. Only if we create a new schema (that is not in cache) we can actually access tables we create during the run. 
We have some ideas, but for now I'm moving this to a [new issue](https://github.com/elementary-data/elementary/issues/285).

**Comment by Vfisa** [comment]
@Maayan-s Can I define a custom schema? I mean I cannot have it as a suffix - I would have a new customschema solely for test tables. Would that work?

```
models:
      
  elementary:
    +meta:
      schema_name: '{{ env_var("DBT_ELEMENTARY_SCHEMA") }}'
      test_schema_name: '{{ env_var("DBT_ELEMENTARY_TEST_SCHEMA") }}'
```

My business requirement is that I can have multiple pre-defined schemas, just not enough rights to create schema on the fly...


Many thanks!

**Comment by Maayan-s** [comment]
@vfisa

The change we introduced today let's you configure the suffix for Elementary schema, using a var.
Going back to your example:
```
models:
  elementary:
    +meta:
      schema_name: '{{ env_var("DBT_ELEMENTARY_SCHEMA") }}'
      test_schema_name: '{{ env_var("DBT_ELEMENTARY_SCHEMA_A") }}'

vars:
  tests_schema_name: '_A'
```  
  
If the schema is already there,  we don't create it on the fly.
