### ISSUE TITLE
Feature - Adding custom descriptions to tests

### ISSUE THREAD

**Issue by hasnan-din** [elementary-data/elementary#279]
It would be great to have custom names & possibly even descriptions as part of the variables used when creating tests. It would help a lot for interpreting results and displaying the outcome to end users!

**Comment by Maayan-s** [comment]
Thank you for opening this issue @hasnan-din!

These are actually 2 feature requests:
1. Custom names for tests
2. Descriptions for tests

About custom names - 
This is supported in dbt since 1.1 and we show the custom name you select in the report. 
Config would look like this:
```
        tests:
          - name: unexpected_order_status    # custom name for test
            test_name: accepted_values      # name of the generic test to apply
```

Does this answer your need? Is there a use case for adding a description as well?

**Comment by Maayan-s** [comment]
In alerts we do not use the custom test name, this requires a fix.
