### ISSUE TITLE
[ELE-48] Support custom test names

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#299]
Since dbt 1.1 custom names for tests are supported.
Config looks like this:

```
        tests:
          - name: unexpected_order_status    # custom name for test
            test_name: accepted_values      # name of the generic test to apply
```

However, we don't use the right field in the API to show this name in the report.

The change:

1. Check if we collect this field in dbt_package elementary_test_restults table. If not - add it.
2. Make API use that field as test name if it exists.

<sub>[ELE-48](https://linear.app/elementary/issue/ELE-48/support-custom-test-names)</sub>

**Comment by Maayan-s** [comment]
This is the similar issue for the alerts - https://github.com/elementary-data/elementary/issues/298

**Comment by amber-owenodoherty** [comment]
Would like to raise awareness on this issue.

Having the ability to separate out the Test name property, rather than the generic macro name, allows a higher fidelity on the Elementary UI, especially for using the same macro but on different grains, such as on a large FACT table. This dovetails nicely into the reusability of generic test cases in DBT/ELE which can target different areas of the business.

Our particular use case is essentially ensuring that Invoices have matching payments. We have a large number of invoices, and the range of values can vary from $100's to much larger amounts. Hence, we also like to group down the grain to see it via Business Unit, Date or any other dimension.

The generic Test case runs very well with an option group_by parameter, but it is masked on the Model run as the Test Name is simply the generic macro. Even expanding this, the only way to discern it is either through the Description meta data or the compiled code.

**Comment by martamassarotti** [comment]
Hey, I would really love to see this implemented soon. In our dbt project we use a lot of expectations for tests and many other generic tests. When we get alerts on slack and they indicate the full name it always takes us a bit to realise which test we are actually talking about, while if we could have custom names that would be immediate and would be very easy to link it to our external documentation and dashboard where we use aliases instead of tests.

**Comment by Maayan-s** [comment]
@oravi @elongl 
Can we try this?
https://github.com/dbt-labs/dbt-core/issues/6470
