### ISSUE TITLE
[ELE-52] Elementary Anomaly Detection tests V2

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#355]
## Why are we reworking our tests?

The main reason is to create a clear contract with users - what is being tested, and what does it mean when a test fails?
Today our anomaly detection tests group monitors, and it’s not clear what is the problem if a specific monitor shows an anomaly.

This is also an opportunity to implement options that we learned are missing in our tests, and make the code more robust and extendable.

## What is this issue for?

We want to get feedback from the community on the new design.
Below you could find the usage docs for the suggested implementation.
In the last section of the page, we detailed our main dilemmas.
Any feedback would be appreciated 🤗

## Anomaly detection tests V2:

Elementary includes **data anomaly detection as dbt tests.**

These tests collect metrics and metadata over time. On each execution, the tests analyze the new data, compare the latest metrics to historical metrics, and alert on anomalies and outliers. These tests are configured and executed like any other tests in your project.

In opposed to other dbt tests which are stateless and are in fact assertions, Elementary anomaly detection tests are stateful. Also, users don’t need to configure limits or expectations.

For example:

When configured for a column, dbt `not_null` test asserts if there are any null values in it and fails if there are. Elementary `nullness` test monitors the rate of null values over time, and fails if there is a significant change in it.

### How to use Elementary anomaly detection tests?

Configure just like any other dbt tests, run using `dbt test` command.

### How each test works?

* Each test builds and executes a query to retrieve metrics and store in a table. A test can group several monitors that collect different metrics, all to detect a similar issue.
  The query parameters are:
  * Time limit by `metric_days_back`, minimum is `backfill_buckets`.
  * Group by `time_bucket` (day, hour, etc) according to `timestamp_column`.
  * If `group_by` expression is provided, group by it as well.
  * if `where` expression is provided, filter by it.
  * If this is a table level test and `include_columns / exclude_columns` is provided, run only on this subset of columns.
  * `monitors` to exclude or include in the test. If undefined, all monitors of the test are used.
* Train an anomalies model / statistical model on metrics on a timeframe limited by `train_days_back` and a specific level of `sensitivity`.
* Test the metrics for a time limited by `test_days_back`, and fail if latest metric is anomalous.

### Available tests - Tables and columns

![](https://uploads.linear.app/56c81801-6242-4fa8-b46c-9e89cdf95c21/6dd2a96c-7470-4228-82b7-c5848e0a9cff/6a220ff4-6326-4371-ad76-94d825117b32)

### Available tests - Dimensions

![](https://uploads.linear.app/56c81801-6242-4fa8-b46c-9e89cdf95c21/743a0a4f-f4b5-4292-a62e-6f725bbbf59a/54d03cb8-3a49-401e-9d7e-030eeb258042)

### Available tests - Custom

![](https://uploads.linear.app/56c81801-6242-4fa8-b46c-9e89cdf95c21/332d3467-5dd6-49ae-b820-f819e3672d96/47c387a6-bcf4-4cb4-a6ee-090612409d74)

### Available configuration

* **Time buckets configuration:**
  * Allows you to define how records are aggregated when calculating metrics. For example, a daily time bucket is ideal for tables that are updated daily.
  * `timestamp_column: str`
    * The column that represents the data creation time, and will be used for bucketing.
  * `time_bucket: str`
    * Size of time bucket. Options: day, hour, week, month.
  * `metric_days_back: int`
    * Limit the metrics collection timeframe, for both performance and relevance reasons.
  * `backfill_buckets: int`
    * The minimal number of buckets for collection of metrics on each run, to handle data delays. For example, for a table that has daily buckets and loads data with up to 1 week of delay, should be configured to 7 buckets.
* **Filtering configuration:**
  * `where: str`
    * Filter the tested data with a SQL where expression.
  * `include_columns / exclude_columns: str`
    * Filter the tested data for table-level tests with selecting or excluding specific columns.
* **Test configuration:**
  * `monitors`
    * Which monitors to activate, if you want to change from default.
  * `group_by: str`
    * Which column or SQL expression to group by.
* **Anomaly detection configuration:**
  * `train_days_back: int`
  * `test_days_back: int`
  * `sensitivity: int`

## Main dilemmas

1. One of the reasons for this change is that today Elementary tests group many monitors, so it's unclear what exactly each test is checking. This new design makes each test a lot more specific, but the tests are still grouping several monitors.
   Should we create a test for each monitor? Does grouping make sense as several monitors are monitoring for the same kind of problem?
2. Should dimension tests be separate tests (defined on the dimension column) or should the users define dimension tests by using `group_by` with regular tests?
3. Which tests are more useful? Which are missing? Which are not useful?

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-52](https://linear.app/elementary/issue/ELE-52/elementary-anomaly-detection-tests-v2)</sub>

**Comment by rloredo** [comment]
Thank you for opening this discussion!

Although I know that Elementary focus is not on the tests themselves I think it's a logical feature for an observability tool. 
However, I'm afraid that it could take a lot of effort that could be invested in another elementary feature.
I would ask you, how can you do something differential that neither dbt nor other maintained package is already doing? and also, how to integrate these features as organically as possible with dbt existent things? 

I think that it makes sense to build Elementary as *the* solution for data testing and observability, but the paths to get to there may differ.

I'll try to share my thoughts about the available tests described as a user but also as a product devil's advocate. I hope it helps!

**volume**
This is a must. However [dbt-expectations](https://github.com/calogica/dbt-expectations) have been working on this and I think they have a laser focus on this. Shouldn't be more logical just to integrate that into how we show the results of the tests of that package?

**freshness**
The freshness tests that dbt implements are limited to saying "it is or it is not fresh". The elementary version of it considers "historical freshness" or "how often does this table update and is the latest update inside a non-significant window of time"? 

I think that this is an added value, but it makes freshness more complex than it should be (just an opinion, because I see freshness as an SLO/SLA if it's within the agreed value it's ok). 

**uniqueness**
I don't understand its value very well. A column should be unique or it shouldn't.  It's up to the analysts or activation layer to say if the ratio of values is off (I'm thinking, for example, if a product is being sold more or smth like that).  I shouldn't focus on it. Perhaps there are some use cases that I'm missing... 

**nullness**
In this case, I think it's a good idea, always depending on what a null value means. I often find myself with more null values because something is missing in a joined table or because the data generator is failing to send that field. I'm not aware of any other package that has this.

**distribution**
I think that here's the biggest differential. Perhaps it's could be simplified a little bit. I have a bucket of data, I want to describe its distribution and see if the new data fits that. I'm thinking more in terms of t-tests or things like that, adapted to different types of distributions. Perhaps it's a good idea to spend more time understanding the "example alerts" column for this (that is missing!).  I'm thinking something along the line of "the probability of the new data of being a sample of the old data is x%" (prior and posterior bayesian fits???). I see a big potential here.

**cardinality**
I don't understand this one very well. How is it different than the `uniqueness` or `distribution` ones? I think that we can make it work along the same idea as the `distribution` one and use chi2 tests.

**string format**

See [this](https://github.com/calogica/dbt-expectations#string-matching) I think it's quite well developed and can be leveraged.

**dimensions**
I don't have a clear use case for these 3 tests. I think they can overlap with `distribution` if we think about that one as I described.

**custom metric**
I think that this could be solved with a `where` parameter in the other tests, but perhaps I'm not understanding very well the use-cases.


I would also like to raise one problem that could also fit into this domain: **test coverage**. I know [this package](https://github.com/slidoapp/dbt-coverage), but it's a pure CLI/pre-commit thing. Perhaps there's a low hanging that could be implemented in the edr to answer the question "what's the test coverage for my project?" "where could I add more *useful* tests?". 


I hope my comments are useful and I'm looking forward to see how this topic evolves!

**Comment by Maayan-s** [comment]
Thank you @rloredo for the thoughtful response! 
I 100% agree with your approach, we must be focused on where we can bring new value in testing. Where the exciting solutions work - we should focus on integrating in the best possible way. 

**Should we have a dbt tests suit?** 
The big differentiator of Elementary tests is that they are monitoring data, in oppose to validating assertions about data (the original purpose of dbt tests). 
I think every stack needs both. 
For example - you talked about freshness, where SLA is a common practice. However, I'm not sure you can define an SLA on each of your models. It doesn't scale. The solution would be to place a freshness monitoring test, that would alert you if your freshness is way off compared to normal. 

**Should we re-build the tests we have now?** 
It has become hard to change and maintain the code, and we have some innovative ideas we can't currently implement without making this change. If we already make the change, let's do it better this time :)

**Specific test**
- volume - Agree that this is a must, I think here it's harder to define your expectations so anomaly detection makes tons of sense. 
- freshness - Yes, do you think SLAs can scale? Anyway in the version released today, we integrated with dbt source-freshness. 
- uniqueness - The question is if uniqueness is binary as you described (unique or not), or is it a range? I guess it's also some version of distribution test, but if you have a non-unique column it can be close to unique (few if any duplications of each value), or far from unique (very few different values repeating). What if the column is usually close to unique, and suddenly that changes? Could indicate that something is wrong. 
- nullness - 👍, perfect use case! 
- distribution - My biggest dilemma here is that there are so many different variations to a distribution change. Should this test group all these different options as these are all distribution problems? Should we provide a different test for each? For example: if we want to find anomalies in a numeric column distribution, we should monitor things like percentiles, max, min, avg.. should it all be under one test? 
- cardinality - a bit different, it's how many different values are there, and not what is their distribution/frequency. It's mostly good for dimension columns, like 'platform', so you could notice if suddenly there is no iOS data. 
- string format - Cool reference!
- dimensions - I agree, distribution is a very wide use case. Should we break it down to more specific tests or not? hard to tell. 
- custom metric - This is to do anomaly detection for you on a metric you provide. Could be one of your KPIs for example. 

**test coverage** - I agree, we are thinking about this as well! This should probably be a different issue.

**Comment by Tilenk** [comment]
+1 on the custom metrics. In most cases the first thing that breaks is the logic that calculates the KPIs. The KPIs are usually on dashboards that are used by our end users (eg. CEO, product team, etc.). We want to detect if we broke a model/calculation during development and inform our end users of the issue. 
Here's an example of how this test could look like.

```
tests:
  - elementary.dimension_anomalies:
      dimensions:
        - country
        - product
      metric: dau
```
Here we monitor the daily active users per product and country.

**Comment by oravi** [comment]
A user asked why we mainly rely on Z-score - 

[https://elementary-community.slack.com/archives/C02CTC89LAX/p1672852023641179](https://elementary-community.slack.com/archives/C02CTC89LAX/p1672852023641179)

**Comment by haritamar** [comment]
Closing since this is a relatively old discussion and some of these changes (though not all) have already been implemented. If relevant, we'll open a new issue.
