### ISSUE TITLE
[ELE-58] Optionally combine slack alerts into a single message

### ISSUE THREAD

**Issue by jakeberesford-palmetto** [elementary-data/elementary#408]
**Is your feature request related to a problem? Please describe.**
When we have multiple test failures due to bad data making its way into our source systems or some coding mistake in a base model, `edr monitor` sends a slack message for each alert. 
This creates a lot of noise in our slack channel, and can seem like a much bigger problem than it really is.

**Describe the solution you'd like**
- Ability to configure grouping for slack notifications, default can remain the same but additional options to group by 'all' and 'table' would be great
- Slack message body would be different, including a count of the alerts and listing the tables, etc. that are alerting.

**Describe alternatives you've considered**
Rolling my own slack notifier, but yours is already very good!

**Would you be willing to contribute this feature?**
Possibly, but my bandwidth will be limited in the short term.

<sub>[ELE-58](https://linear.app/elementary/issue/ELE-58/optionally-combine-slack-alerts-into-a-single-message)</sub>

**Comment by oravi** [comment]
Thanks for opening this @jakeberesford-palmetto!

Indeed sending an alert per failure could work when you have a small number of test / model failures. The big advantage for doing so is that each alert can be very detailed with tons of useful information when you do the troubleshooting. The downside as mentioned here is that it could be too much for when you all of sudden have a spike of failures due to incidents.

I think there could be several different approaches here -

Group alerts by errors - send a detailed alert per error with a list of relevant models / tests. This requires further scoping but the idea is to have a solution for spikes due to the same error.

Group alerts by table - if you have multiple tests running on the same table, send a list of failed tests for the same table in a single alert. This could help if you have lots of tests defined per table.

Group all alerts into a single alert - this can enable receiving a single alert for all the failures during the last run. The downside here is that the granularity for each error could be limited. To solve that we can attach the report and then further troubleshooting can be done using the report itself. 

Would love to hear your thoughts!

I'll add it to the ticket as well. Would love to hear your thoughts about it

**Comment by jakeberesford-palmetto** [comment]
I think those groupings make a lot of sense. I can see value in all 3, do you think it'd be possible for elementary to determine the best grouping given a list of alerts?

Perhaps there might be a configurable threshold where tests are grouped? If I just have 1 or 2 alerts, the existing alerts are great, but if I have 3+ alerts I'd prefer them to be rolled up into a single alert.

For the aggregated alerts I'd want to see more of a summary, the number of alerts, a query to get specific alert details from the data warehouse, and a link to the edr report would be nice!

**Comment by Hadarsagiv** [comment]
Hey @jakeberesford-palmetto - we added the ability to group alerts by table! 
You can see the details on our [docs](https://docs.elementary-data.com/quickstart/send-slack-alerts#notification-settings-decide-how-you-want-to-get-your-alerts) under the "Group alerts by table" section.
