### ISSUE TITLE
[Feature] Support multiple BigQuery projects

### ISSUE THREAD

**Issue by yu-iskw** [elementary-data/elementary#48]
## Motivation
As we use multiple GCP projects to execute BigQuery queries, we would like to visualize them all together.

**Comment by Maayan-s** [comment]
Hi @yu-iskw ,
We support cross projects lineage, I think the reason it didn't work is the bug you fixed with the quoting (thanks for that :)).
It is already in master, I will let you know when we release a new version with it later today so you could update and try it. 

The flow for creating a cross-projects lineage would be:
```
## Generate a lineage graph from query logs of the databases (projects) db1,db2
## make sure you don't have white spaces between the project names:

edr lineage generate -dbs db1,db2
```

This will create a local file with the lineage from both projects. You can filter on dates as well.
Next use the lineage command and filters to visualize:
```
## Visualize the lineage graph created in the previous command
## (cached in a local file)

edr lineage -o true
```

Note that to create a new local file you need to run `edr lineage generate `again.

**Comment by Maayan-s** [comment]
@yu-iskw 
Thanks for the recommendations on the graph visualization alternatives, we are exploring how to improve the UI, we know that networkx has its limitations. I'll take a look at your recommendations for it!
As a mean to overcome this until than, we separated the graph generation (extract queries, parse, build graph) and the visualization (filter and visualize) into two different commands.
Our assumption was that if the graph is too big for networkx, it is also too big for a person to work with it.
So the flow is `edr lineage generate` to create a big graph (creates a local pickle file) -> then `edr lineage --table +<table_name>+` or any other filter, to visualize the part of the graph you want to see at the moment. This means you can iterate on the same graph with different filters fast (because you filter against a local file).
If you try to open use the pickle with a different visualizations and get better results I would love to hear about that :)

The open-browser command does not always work, it depends on the process you used to execute edr and whether it has permissions to launch a browser or not.

**Comment by yu-iskw** [comment]
It sounds good to separate the features as independent commands. As for me, it would be awesome if we can specify an output format.

**Comment by yu-iskw** [comment]
By the way, as I understand the feature, I close the issue.
