### ISSUE TITLE
[ELE-98] Validate elementary against a range of dbt versions (including RC versions) in CI

### ISSUE THREAD

**Issue by oravi** [elementary-data/elementary#544]
<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-98](https://linear.app/elementary/issue/ELE-98/validate-elementary-against-a-range-of-dbt-versions-including-rc)</sub>

**Comment by elongl** [comment]
Here are the changes:

* [Scheduled test jobs use dbts pre-releases.](https://github.com/elementary-data/elementary/commit/5cfeac6a3ef44e5dc8e620246102253d11e326bc)
* [Using dbt 1.1.0 for tests on PRs.](https://github.com/elementary-data/elementary/commit/76088a35fe1bd356680c4db29dbf38d545571336)
* [Integration tests use dbt utils based on dbt version.](https://github.com/elementary-data/dbt-data-reliability/commit/884e47aae8aa795852416059692c65e7c4167065)
* [Using dbt 1.1.0 for tests on PRs.](https://github.com/elementary-data/dbt-data-reliability/commit/b261ca3a69a0ecac76557241a857fc2ad3102fb5)

**Comment by oravi** [comment]
@elongl why 1.1.0?

**Comment by elongl** [comment]
@oravi 

[1.0.0 is broken](https://github.com/elementary-data/dbt-data-reliability/actions/runs/3883045423).

**Comment by oravi** [comment]
oh, do we know why?

**Comment by elongl** [comment]
[Yes](https://github.com/dbt-labs/dbt-core/issues/4745), their specifier for the `markupsafe` library was too broad and broke compatibility.

![image.png](https://uploads.linear.app/56c81801-6242-4fa8-b46c-9e89cdf95c21/ea2117a6-45c5-4591-81d1-57fe6f688c20/b794a4a3-c61f-4953-a48b-00edf8ef5627)

Looking at this issue, I believe I could use v1.0.2 however instead of 1.1.0.

**Comment by oravi** [comment]
Cool!
