### ISSUE TITLE
[ELE-173] Add `dbt_seeds` model

### ISSUE THREAD

**Issue by frannydelaney** [elementary-data/elementary#563]
**Is your feature request related to a problem? Please describe.**
For models and sources, we have `dbt_models` and `dbt_sources` to join to to gather more information about them (such as name, schema etc). This however doesn't exist for `dbt_seeds`. This came up when creating a pre-joined version of `elementary_test_results` where the `model_unique_id` for tested seeds has no where to join to.

**Describe the solution you'd like**
Create `dbt_seeds` with relevant seed information, much like `dbt_models` and `dbt_sources` and `dbt_tests` etc

**Describe alternatives you've considered**
Don't think the data is anywhere else, that I've found at least

**Additional context**
[Slack convo here](https://elementary-community.slack.com/archives/C02CTC89LAX/p1673628649610999) (slack convo mostly unrelated, but where this came up)

**Would you be willing to contribute this feature?**
Sure, though I've never contributed to an open source project before 😅 

<sub>[ELE-173](https://linear.app/elementary/issue/ELE-173/add-dbt-seeds-model)</sub>

**Comment by Maayan-s** [comment]
Hi @frannydelaney,
We discussed it and it is a natural addition to the package. 
And we would be honored to be the first project you contribute to! 

The first step is to decide which fields we want the table to have. 
Here is a seed graph node:
```
{'alias': 'raw_products',
 'build_path': None,
 'checksum': {'checksum': 'seeds/raw_products.csv', 'name': 'path'},
 'columns': {},
 'config': {'alias': None,
            'column_types': {},
            'database': None,
            'docs': {'node_color': None, 'show': True},
            'enabled': True,
            'full_refresh': None,
            'grants': {},
            'incremental_strategy': None,
            'materialized': 'seed',
            'meta': {},
            'on_schema_change': 'ignore',
            'packages': [],
            'persist_docs': {},
            'post-hook': [],
            'pre-hook': [],
            'quote_columns': None,
            'quoting': {},
            'schema': 'seeds',
            'tags': [],
            'unique_key': None},
 'config_call_dict': {},
 'created_at': 1673978902.9003599,
 'database': 'postgres',
 'deferred': False,
 'description': '',
 'docs': {'node_color': None, 'show': True},
 'fqn': ['playground', 'raw_products'],
 'meta': {},
 'name': 'raw_products',
 'original_file_path': 'seeds/raw_products.csv',
 'package_name': 'playground',
 'patch_path': None,
 'path': 'raw_products.csv',
 'raw_code': '',
 'relation_name': '"postgres"."elon_test_seeds"."raw_products"',
 'resource_type': 'seed',
 'root_path': '/Users/egk/work/dbt/dbt-playground',
 'schema': 'elon_test_seeds',
 'tags': [],
 'unique_id': 'seed.playground.raw_products',
 'unrendered_config': {'schema': 'seeds'}}
```

Based on what we store today for models, the minimal structure should be:
```
unique_id
alias
checksum
tags
meta
owner
database_name
schema_name
description
name
package_name
original_path
path
generated_at
```

Any other fields you see on the node you think should be in the table?

**Comment by frannydelaney** [comment]
@Maayan-s that looks good, I don't see anything else that would be obviously useful to include everywhere

**Comment by elongl** [comment]
Hi @frannydelaney, thanks a lot for opening this issue.
I'd like to provide some guidance that will help you with the implementation.
First of all, if this is your first contribution, I recommend taking a look at [this guide](https://github.com/firstcontributions/first-contributions).

You can test your changes by installing the package locally via the [`local` installation method](https://docs.getdbt.com/docs/build/packages#local-packages), or you can leave that to us and that's also totally okay!

Here are the steps required in order to implement the feature:
1. Create the `dbt_seeds` model under [`models/edr/dbt_artifacts`](https://github.com/elementary-data/dbt-data-reliability/tree/f1ae297f2a698b24604e4521b3c221688d05e10b/models/edr/dbt_artifacts). It should basically look exactly like `dbt_models` only with `seed` anywhere instead of `model`.
2. Create the `upload_dbt_seeds` macro under [`macros/edr/dbt_artifacts`](https://github.com/elementary-data/dbt-data-reliability/tree/57928e831336be8f4b51d91660a7fd1f20dd9ca1/macros/edr/dbt_artifacts). Once again, everything should be rather similiar to `upload_dbt_models` only with `seeds` instead. You should also pay attention to define the correct columns in `get_dbt_seeds_empty_table_query`.
3. Make `flatten_seed` return the appropriate columns according to the JSON above.

Thanks a lot.
Please let me know if you have any questions.

**Comment by frannydelaney** [comment]
Hi @elongl and @Maayan-s , I opened up a PR, not sure if I did everything according to the right process, but I was able to test locally and got the expected output. Please let me know if I should do anything differently, thanks!
