### ISSUE TITLE
Ability to customize the model aliases within our own `dbt_project.yml` files

### ISSUE THREAD

**Issue by aayush1973** [elementary-data/elementary#717]
**Is your feature request related to a problem? Please describe.**
I work for a digital marketing agency where we use `dbt` for data transformation and want to use the `elementary` package to track our model and sources metadata. Currently, the elementary models do not allow us to rename them in our own `dbt_project.yml` files. For example, we want to alias the `dbt_invocations` model as `metadata__invocations` but the `dbt build` doesn't insert rows into the table because the relation only points to tables named `dbt_invocations`. 

**Describe the solution you'd like**
Ability to rename the models and customize the models in our own `dbt_project.yml` files.

**Describe alternatives you've considered**
No alternate solutions considered so far

**Additional context**
N/A

**Would you be willing to contribute this feature?**
I will be willing to contribute to the addition of this feature if required.

**Comment by RoiTabach** [comment]
@aayush1973 
Did you try creating a view on top of the Elementary models with names that you easily control?

**Comment by aayush1973** [comment]
> Did you try creating a view on top of the Elementary models with names that you easily control?

Yeah we did consider that but not necessarily as a 'solution' but more so as a band-aid fix. We don't want to make our base repo too clunky by adding in non-platform related models. This is why we were thinking if there was a way to achieve this without making our own views.

**Comment by Maayan-s** [comment]
Hi @aayush1973 ,
Thanks for sharing your use case!
Configuring an alias in the `dbt_project.yml` file worked for me with the full model path:
```
models:
  elementary:
    +schema: elementary
    edr:
      dbt_artifacts:
        dbt_invocations:
          alias: 'metadata_invocations'

```

I'm not sure if this will not cause other problems, but you are welcome to try it.
For sure the Elementary CLI (that creates the UI and alerts) will not work if you make this change.
If you only plan to use the dbt package, I believe this solves your use case :)

Because the dbt-package tables are used by the CLI, we can not support changing the table names as a feature. 
Hence, I'm closing this issue as `not planned`.
