### ISSUE TITLE
[ELE-716] Report fails to generate if owner is configured as dict (exposures format)

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#827]
**Describe the bug**
We expect a string or list of strings in the owner field for sources. 
For other format, we fail. 
Example: {"name":   "Maayan Salom", "email":   "maayan@elementary-data.com"}

**To Reproduce**
Configure source owner like this:
```
owner:
  name: name
  email: email@gmail.com
```

**Expected behavior**
We shouldn't crush on it, even if we don't support thr format. 

**Screenshots**
<img width="813" alt="image" src="https://user-images.githubusercontent.com/22072028/233999471-7c713907-1805-4cc8-9e38-e2ebca01e10d.png">

<sub>[ELE-716](https://linear.app/elementary/issue/ELE-716/report-fails-to-generate-if-owner-is-configured-as-dict-exposures)</sub>

**Comment by manulpatel** [comment]
Hi! @Maayan-s. I would be happy to fix this issue. To display the owner as it is in case of dict, we need to pass an exception for Error **1** , here. 
https://github.com/elementary-data/elementary/blob/1c88fd481816595a5e8a8463d8eed1019469a339/elementary/monitor/data_monitoring/report/data_monitoring_report.py#L111

What do you suggest?

**Comment by Maayan-s** [comment]
Thank you @manulpatel !
@IDoneShaveIt could you please take a look and let @manulpatel know if this is the way to go for fixing this?

**Comment by IDoneShaveIt** [comment]
Hey @manulpatel, sorry for the late reply!
I think that handling the error at the `DataMonitoringReport.get_report_data` won't do the trick because the error that we are occurring might break the rest of the report data generation.

The error that we get is a `pydantic` error where we pass data that does not match a `pydantic` schema (in our case we pass a dict when the schema expects a list of strings).

The schema that is throwing the error is [ArtifactSchema](https://github.com/elementary-data/elementary/blob/master/elementary/monitor/fetchers/models/schema.py#L27).
It is using a method called `_load_var_to_list` at the `load_owners` [validator](https://github.com/elementary-data/elementary/blob/master/elementary/monitor/fetchers/models/schema.py#L43).

We need to edit [_load_var_to_list](https://github.com/elementary-data/elementary/blob/master/elementary/utils/schema.py#L20) to handle our case when our owner is a string of a dict `'{"name": "text", "email": "text"}'`.
To do so, we need to check the output of [try_load_json](https://github.com/elementary-data/elementary/blob/master/elementary/utils/schema.py#L26) and if it's a dict, we should do one of the 2:

1. Return an empty list (because we don't know what are the keys of the dict)
2. `json.dumps` the dict and return it as an item of a list (that way we will return the whole data of the dict)

I prefer option 2 because that way we won't "lose" data.

@manulpatel thank you again for willing to fix this issue! I am here to help with any question, and hope this made the error clearer 🙂
